### ISSUE TITLE
Paper Typo?

### ISSUE THREAD

**Issue by bainro** [ybkscht/EfficientPose#26]
![image](https://user-images.githubusercontent.com/31903812/119233394-b14bb680-badd-11eb-95bb-0e38a28d9147.png)

The default # of epochs in train.py is 500. Is the 5,000 epochs in the paper a typo? 500 epochs of training already takes several days on my 2080 GPU. 

Also, epoch is defined as 1,790. Usually epoch is defined as 1 loop thru the whole training set, thus changing the mini-batch size would change number of steps in an epoch. Is there a reason why epoch is defined differently in this repo?

Thanks ybkscht!

**Comment by ybkscht** [comment]
Hi @bainro ,

no the 5000 epochs mentioned in the paper is actually correct.  
This is because the Linemod training set is very small (I think it was 179 examples for the driller object) and to avoid too much validation overhead, we decided to evaluate the model only every 10 epochs (which is also mentioned in the paper). 
Therefore, we increased the number of steps per epoch in the training script from 179 to 1790 and reduced the number of epochs from 5000 to 500.
But you are right, if changing the batch size the steps per epoch have to be changed accordingly.

Sincerely,
Yannick
