### ISSUE TITLE
Loss nonconvergence

### ISSUE THREAD

**Issue by rush9838465** [ybkscht/EfficientPose#6]
I train my data set, what's the reason why the loss doesn't converge you know?But mAP is good.

![11](https://user-images.githubusercontent.com/10445182/103605920-19936480-4f50-11eb-9304-5727e2930835.png)
![22](https://user-images.githubusercontent.com/10445182/103605925-1bf5be80-4f50-11eb-81b7-d62464f87c2d.png)
![33](https://user-images.githubusercontent.com/10445182/103605926-1c8e5500-4f50-11eb-91fc-3f8a4e5b819e.png)

**Comment by ybkscht** [comment]
Hi rush,

The jump in the classification and regression loss is strange but the mAP is still near 1.0, so the 2D detection task is still doing well and I think this shouldn't be the main problem here (classification and regression losses are from the 2D detection part and the mAP is a metric for it).
The transformation loss (which is for the 6D pose estimation part) instead is decreasing but when looking at the 6D pose estimation metrics like ADD, they start to increase very slowly.
From my experience the absolute value of the transformation loss should be much higher (factor 100x - 1000x) and I could imagine that your dataset unit is different from Linemod which uses mm.
If this is the case, you need to change the translation_scale_norm parameter in the generator according to the unit of your dataset and probably the transformation loss weight (in train.py) from 0.02 to something greater because the transformation loss becomes otherwise too small relative to the other losses.
EfficientPose works internally with meter but the output is scaled with the translation_scale_norm parameter. For example when using Linemod which is in mm, the translation_scale_norm parameter is set to 1000 (which is also the default).
But that's just a guess and hard to say if this is really the problem without more information about your dataset and training parameters.

Did you use the debug.py script to check wheter the images and annotations of your custom dataset are loaded as expected? This also can help a lot in such scenarios.

I hope this helps you.

Sincerely,
Yannick

**Comment by rush9838465** [comment]
You are quite right. I used the unit of meter, and I changed it by 0.02 at noon. I will see the effect tomorrow. I'll try Debug.py later. Thank you very much!




---Original---

**Comment by ghoshaw** [comment]
Hi, I also train my own data, but the loss seems strange either.
![image](https://user-images.githubusercontent.com/23494873/104113677-d31a7d00-5336-11eb-8191-1db728e978df.png)
![image](https://user-images.githubusercontent.com/23494873/104113679-dca3e500-5336-11eb-8582-1a5ab25cf185.png)
![image](https://user-images.githubusercontent.com/23494873/104113681-e0d00280-5336-11eb-8c6f-acd258794d74.png)
![image](https://user-images.githubusercontent.com/23494873/104113687-e4638980-5336-11eb-92c5-a8edfe766a14.png)
![image](https://user-images.githubusercontent.com/23494873/104113690-e88fa700-5336-11eb-8a62-86a6e6a21a9a.png)
![image](https://user-images.githubusercontent.com/23494873/104113692-ed545b00-5336-11eb-8845-d780d1cc43e8.png)
![image](https://user-images.githubusercontent.com/23494873/104113694-f1807880-5336-11eb-9825-e0cfc3f558a8.png)
BTW, my data is in meter, so I set the translation_scale_norm to 1, and the loss weight is still 0.02, and I find that the scale of loss between the 2D detect and pose estimating is not that large. I also use the debug.py to show the data, the result seems ok, except for that the 3D points order I used is different from the origin code. I random set the 3D points order, but I think this should not be an issue, because I find that the result saved in training process can plot the point correctly, it is just the pose estimate is not accurate. So any advice for my training? Thanks a lot!

**Comment by rush9838465** [comment]
@ghoshaw  My previous problem was caused by extrinsic matrix error. If debug.py shows that your 3D bounding box is normal, it indicates that your extrinsic matrix should have no problem. But I changed 0.02 to 5.

**Comment by ghoshaw** [comment]
@rush9838465 , in your case, the loss of transformation is smaller than the 2d detect loss, but in my case, my transformation loss is larger than 2d detect loss, So I think I should change 0.02 t0 0.002?

**Comment by rush9838465** [comment]
@ghoshaw  I think it can be left unchanged, your loss is pretty low. Have you tried inference?

**Comment by ghoshaw** [comment]
I did not try inference, but the image saved in training process is not that good. 
And I just find a bug, I accidentally freeze the backbone, and I will try to do a new experiment. Thanks for your answer!
